RFC #70: Migrate FDO Common to VS 2015
Special tasks:
Fdo\Unmanaged\Src\Common\Io\FileStream.cpp
FILE Encapsulation 
In previous versions, the FILE type was completely defined in <stdio.h>, so it was possible for user code to reach into a FILE and modify its internals. The stdio library has been changed to hide implementation details. As part of this, FILE as defined in <stdio.h> is now an opaque type and its members are inaccessible from outside of the CRT itself.
-> Figure out read/write capabilities with fstat.st_mode, which gives only the status of the file on the disc but not the real time opened mode
-> This is different to the previous FILE property "_flag", which is not available anymore since c++ v140.

Utilities\ExpressionEngine\Src\Util\FdoExpressionEngineUtilDataReader.cpp
error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning
-> use "unordered_map" instead of "hash_map"

git-svn-id: http://svn.osgeo.org/fdo/sandbox/v140@7259 d98eaee6-4212-0410-900c-dcc49bf69b99